# Generated by Django 5.1.6 on 2025-03-04 17:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('normal_balance', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_account_number', message='Account number must be exactly 6 digits.', regex='^\\d{6}$')])),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived'), ('FROZEN', 'Frozen'), ('PENDING', 'Pending Approval')], db_index=True, default='PENDING', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('status_change_date', models.DateField(blank=True, null=True)),
                ('status_change_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounts.account')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accounttype')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AccountStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived'), ('FROZEN', 'Frozen'), ('PENDING', 'Pending Approval')], max_length=20)),
                ('effective_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='accounts.account')),
            ],
            options={
                'verbose_name_plural': 'Account status histories',
                'ordering': ['-effective_date', '-created_at'],
                'indexes': [models.Index(fields=['account', 'effective_date'], name='accounts_ac_account_9e744e_idx')],
            },
        ),
    ]
