# Generated by Django 5.1.6 on 2025-03-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='requested_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='requested_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('PENDING_APPROVAL', 'Pending Approval'), ('PENDING_ARCHIVAL', 'Pending Archival'), ('PENDING_UNARCHIVAL', 'Pending Unarchival')], db_index=True, default='PENDING_APPROVAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountstatushistory',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('PENDING_APPROVAL', 'Pending Approval'), ('PENDING_ARCHIVAL', 'Pending Archival'), ('PENDING_UNARCHIVAL', 'Pending Unarchival')], max_length=20),
        ),
    ]
